language: php
php:
  - "7.1.8"
before_install: 
  - php /home/travis/.phpenv/versions/5.6/bin/composer self-update
services: 
  - mysql
before_script:
  - composer install
script:
  - phpunit -- configuration phpunit.xml --coverage-text
deploy:
  api_key:
    secure: rin14+03W7sa5QsERFte6KWWtu9UXqD2Swa1pF44R55la10lYsxJ8C+55CSVQ3YoLlg4mcj75OFHptHFlxA89T+eiOIqxvq8tFgYxaG0qPCsbtIPyewBsiZNTS/HlQtzpUdNBCGPHfcyLH54uIJKTAGvM1SN34c2qyDqvYKyNnhrWRcmduxAopwvGqjdaO3vPk4vy/I9/egX489U+8LXkNnAPyfxbd9Rwo74KRaEpO9902aCVI1guDpqWbLfP0XpnlY+kyrs39eR8EsA08MI5kUNw+pa5/Ep9tshTFjssz43mnl+sEEhjba9MW29Gin5yfOqPjlLeGAaLjpc5Ry011lWv/QzL1T6alH5rBeKNtIebfGmJDpAwPjdmhaHvTgR+UDpuQvW7ra0Q3qCsPHhAt3lp6WfNabMPr+SBk2f1dXuHFcsgBmukweDclDXCZABUynBi447klaowVL8teu2RbSpqEzC3bPKYdM8rxWFuuiCmlsg4NZjel+nXaXGFSUZO2LH+3eonZ2oDMFAnGSEcLjKY6POsqMejDaSspZN6KivBw/Wmg6C2xTbvl9/bLTSlw7B2/3via6nDGL+4DXZkopn0uoA+Lb/RrKeY/80sbDMOuw5tUJa640DuqEpKPZb3b46rJL177jjFSBjsyv3QlbPeO58v+6lqC5AolHW7dY=
